# Generated by Django 5.0.4 on 2024-07-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_business_address', to='users.address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='home_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_home_address', to='users.address'),
        ),
    ]
