# Generated by Django 5.0.4 on 2024-07-18 16:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_personalinformation_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, unique=True),
        ),
    ]
