# Generated by Django 5.0.4 on 2024-07-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Man'), ('FEMALE', 'Woman'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
