# Generated by Django 5.0.4 on 2024-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_personalinformation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_place',
            field=models.TextField(blank=True, default=('MALE', 'Man')),
        ),
    ]
