# Generated by Django 5.0.4 on 2024-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_personalinformation_birth_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='birth_place',
            field=models.CharField(blank=True, default='Paris', max_length=256),
        ),
    ]
