# Generated by Django 5.0.4 on 2024-07-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_activity_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysector',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivitySector',
        ),
    ]
