# Generated by Django 5.0.4 on 2024-07-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='post_payment',
            field=models.SmallIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='post_payment',
            field=models.SmallIntegerField(max_length=6, null=True),
        ),
    ]
