# Generated by Django 5.0.4 on 2024-07-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_post_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.SmallIntegerField(max_length=4, unique=True),
        ),
    ]
