# Generated by Django 5.0.4 on 2024-07-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='post_payment',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='post_payment',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
