# Generated by Django 5.0.4 on 2024-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sub_id',
            field=models.IntegerField(null=True),
        ),
    ]
