# Generated by Django 5.0.4 on 2024-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_activity_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='to_be_reviewed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='has_children',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='to_be_reviewed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
