# Generated by Django 5.0.4 on 2024-07-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysector',
            name='connector_activity_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='jqpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsectors', to='core.activity'),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='post_payment',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='sub_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='to_be_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitysector',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
