# Generated by Django 5.0.4 on 2024-07-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_activitysector_connector_activity_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitySector',
            new_name='SubActivity',
        ),
    ]
