# Generated by Django 5.0.4 on 2024-07-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_activitysector_subactivity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Sector',
        ),
        migrations.RenameModel(
            old_name='SubActivity',
            new_name='SubSector',
        ),
        migrations.RenameIndex(
            model_name='sector',
            new_name='core_sector_sub_id_b7cd92_idx',
            old_name='core_activi_sub_id_b731ae_idx',
        ),
        migrations.RenameIndex(
            model_name='sector',
            new_name='core_sector_name_21a322_idx',
            old_name='core_activi_name_d6f9ca_idx',
        ),
    ]
