# Generated by Django 5.0.4 on 2024-07-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_activity_sector_rename_subactivity_subsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsector',
            name='has_children',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='jqpa',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
