# Generated by Django 5.0.4 on 2024-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_subsector_has_children_alter_subsector_jqpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsector',
            name='name',
            field=models.CharField(default='Autre', max_length=256),
        ),
    ]
