# Generated by Django 5.0.4 on 2024-07-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_businessactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='sector',
            field=models.ForeignKey(default='Autre', help_text="Domaine d'activité", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector'),
        ),
        migrations.AlterField(
            model_name='businessactivity',
            name='sub_sector',
            field=models.ForeignKey(default='Autre', help_text="Secteur d'activité", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subsector'),
        ),
    ]
