# Generated by Django 5.0.4 on 2024-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_businessactivity_is_micro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessactivity',
            name='business_choice',
        ),
        migrations.RemoveField(
            model_name='businessactivity',
            name='is_micro',
        ),
        migrations.RemoveField(
            model_name='businessactivity',
            name='sub_sector',
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='activity_type',
            field=models.CharField(choices=[('micro', 'Oui, micro-entreprise / entrepreneur individuel'), ('autre', 'Oui, EURL, SARL, SASU, SAS, etc.'), ('non', 'Non')], default='non', max_length=20, verbose_name='Avez-vous déjà exercé une activité non-salariée ?'),
        ),
    ]
