# Generated by Django 5.0.4 on 2024-07-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_businessactivity_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='sector',
            field=models.ForeignKey(default='Non', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector', verbose_name="Domaine d'activité"),
        ),
    ]
