# Generated by Django 5.0.4 on 2024-07-31 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_businessactivity_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='activity_type',
            field=models.CharField(choices=[('non', 'Non'), ('micro', 'Oui, micro-entreprise / entrepreneur individuel'), ('autre', 'Oui, EURL, SARL, SASU, SAS, etc.')], default='non', max_length=20, verbose_name='Avez-vous déjà exercé une activité non-salariée ?'),
        ),
        migrations.AlterField(
            model_name='businessactivity',
            name='sector',
            field=models.ForeignKey(default='non', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector', verbose_name="Domaine d'activité"),
        ),
    ]
