# Generated by Django 5.0.4 on 2024-08-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_businessaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaddress',
            name='country',
            field=models.ForeignKey(blank=True, default='France', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
