# Generated by Django 5.0.4 on 2024-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_active_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('KBIS', 'Kbis'), ('Other', 'Other')], default='KBIS', editable=False, max_length=10),
        ),
    ]
